name: Build Documentation
on:
  push:
    branches:
      - docgen
  workflow_dispatch:

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run my action
        uses: ./
        with:
          repository-path: "nanos-world/api"
          github-token: ${{ github.token }}
